/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TemporalLogicRuntimeModule extends AbstractTemporalLogicRuntimeModule {
}
