/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTemporalLogicScopeProvider extends DelegatingScopeProvider {
}
