/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl.temporalLogic;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.Model#getLocation <em>Location</em>}</li>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.Model#getProperty1 <em>Property1</em>}</li>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.Model#getProperty2 <em>Property2</em>}</li>
 * </ul>
 *
 * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Location</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' containment reference.
   * @see #setLocation(Import)
   * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getModel_Location()
   * @model containment="true"
   * @generated
   */
  Import getLocation();

  /**
   * Sets the value of the '{@link org.eclipse.uml.verification.tl.temporalLogic.Model#getLocation <em>Location</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' containment reference.
   * @see #getLocation()
   * @generated
   */
  void setLocation(Import value);

  /**
   * Returns the value of the '<em><b>Property1</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.uml.verification.tl.temporalLogic.Property1}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property1</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property1</em>' containment reference list.
   * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getModel_Property1()
   * @model containment="true"
   * @generated
   */
  EList<Property1> getProperty1();

  /**
   * Returns the value of the '<em><b>Property2</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.uml.verification.tl.temporalLogic.Property2}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property2</em>' containment reference list.
   * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getModel_Property2()
   * @model containment="true"
   * @generated
   */
  EList<Property2> getProperty2();

} // Model
