/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl.temporalLogic;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.Property2#getModelElement2 <em>Model Element2</em>}</li>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.Property2#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getProperty2()
 * @model
 * @generated
 */
public interface Property2 extends Option
{
  /**
   * Returns the value of the '<em><b>Model Element2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model Element2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Element2</em>' attribute.
   * @see #setModelElement2(String)
   * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getProperty2_ModelElement2()
   * @model
   * @generated
   */
  String getModelElement2();

  /**
   * Sets the value of the '{@link org.eclipse.uml.verification.tl.temporalLogic.Property2#getModelElement2 <em>Model Element2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model Element2</em>' attribute.
   * @see #getModelElement2()
   * @generated
   */
  void setModelElement2(String value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Next</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(Option)
   * @see org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage#getProperty2_Next()
   * @model containment="true"
   * @generated
   */
  Option getNext();

  /**
   * Sets the value of the '{@link org.eclipse.uml.verification.tl.temporalLogic.Property2#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(Option value);

} // Property2
