/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl.temporalLogic.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.uml.verification.tl.temporalLogic.Option;
import org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Option</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.impl.OptionImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.impl.OptionImpl#getModelElement1 <em>Model Element1</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OptionImpl extends MinimalEObjectImpl.Container implements Option
{
  /**
   * The default value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected static final String OPERATOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected String operator = OPERATOR_EDEFAULT;

  /**
   * The default value of the '{@link #getModelElement1() <em>Model Element1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelElement1()
   * @generated
   * @ordered
   */
  protected static final String MODEL_ELEMENT1_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModelElement1() <em>Model Element1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelElement1()
   * @generated
   * @ordered
   */
  protected String modelElement1 = MODEL_ELEMENT1_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OptionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TemporalLogicPackage.Literals.OPTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOperator()
  {
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperator(String newOperator)
  {
    String oldOperator = operator;
    operator = newOperator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporalLogicPackage.OPTION__OPERATOR, oldOperator, operator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getModelElement1()
  {
    return modelElement1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setModelElement1(String newModelElement1)
  {
    String oldModelElement1 = modelElement1;
    modelElement1 = newModelElement1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporalLogicPackage.OPTION__MODEL_ELEMENT1, oldModelElement1, modelElement1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.OPTION__OPERATOR:
        return getOperator();
      case TemporalLogicPackage.OPTION__MODEL_ELEMENT1:
        return getModelElement1();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.OPTION__OPERATOR:
        setOperator((String)newValue);
        return;
      case TemporalLogicPackage.OPTION__MODEL_ELEMENT1:
        setModelElement1((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.OPTION__OPERATOR:
        setOperator(OPERATOR_EDEFAULT);
        return;
      case TemporalLogicPackage.OPTION__MODEL_ELEMENT1:
        setModelElement1(MODEL_ELEMENT1_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.OPTION__OPERATOR:
        return OPERATOR_EDEFAULT == null ? operator != null : !OPERATOR_EDEFAULT.equals(operator);
      case TemporalLogicPackage.OPTION__MODEL_ELEMENT1:
        return MODEL_ELEMENT1_EDEFAULT == null ? modelElement1 != null : !MODEL_ELEMENT1_EDEFAULT.equals(modelElement1);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(", modelElement1: ");
    result.append(modelElement1);
    result.append(')');
    return result.toString();
  }

} //OptionImpl
