/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl.temporalLogic.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.uml.verification.tl.temporalLogic.Option;
import org.eclipse.uml.verification.tl.temporalLogic.Property2;
import org.eclipse.uml.verification.tl.temporalLogic.TemporalLogicPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property2</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.impl.Property2Impl#getModelElement2 <em>Model Element2</em>}</li>
 *   <li>{@link org.eclipse.uml.verification.tl.temporalLogic.impl.Property2Impl#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Property2Impl extends OptionImpl implements Property2
{
  /**
   * The default value of the '{@link #getModelElement2() <em>Model Element2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelElement2()
   * @generated
   * @ordered
   */
  protected static final String MODEL_ELEMENT2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getModelElement2() <em>Model Element2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelElement2()
   * @generated
   * @ordered
   */
  protected String modelElement2 = MODEL_ELEMENT2_EDEFAULT;

  /**
   * The cached value of the '{@link #getNext() <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNext()
   * @generated
   * @ordered
   */
  protected Option next;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Property2Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TemporalLogicPackage.Literals.PROPERTY2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getModelElement2()
  {
    return modelElement2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setModelElement2(String newModelElement2)
  {
    String oldModelElement2 = modelElement2;
    modelElement2 = newModelElement2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporalLogicPackage.PROPERTY2__MODEL_ELEMENT2, oldModelElement2, modelElement2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Option getNext()
  {
    return next;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNext(Option newNext, NotificationChain msgs)
  {
    Option oldNext = next;
    next = newNext;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TemporalLogicPackage.PROPERTY2__NEXT, oldNext, newNext);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNext(Option newNext)
  {
    if (newNext != next)
    {
      NotificationChain msgs = null;
      if (next != null)
        msgs = ((InternalEObject)next).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TemporalLogicPackage.PROPERTY2__NEXT, null, msgs);
      if (newNext != null)
        msgs = ((InternalEObject)newNext).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TemporalLogicPackage.PROPERTY2__NEXT, null, msgs);
      msgs = basicSetNext(newNext, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TemporalLogicPackage.PROPERTY2__NEXT, newNext, newNext));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.PROPERTY2__NEXT:
        return basicSetNext(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.PROPERTY2__MODEL_ELEMENT2:
        return getModelElement2();
      case TemporalLogicPackage.PROPERTY2__NEXT:
        return getNext();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.PROPERTY2__MODEL_ELEMENT2:
        setModelElement2((String)newValue);
        return;
      case TemporalLogicPackage.PROPERTY2__NEXT:
        setNext((Option)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.PROPERTY2__MODEL_ELEMENT2:
        setModelElement2(MODEL_ELEMENT2_EDEFAULT);
        return;
      case TemporalLogicPackage.PROPERTY2__NEXT:
        setNext((Option)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TemporalLogicPackage.PROPERTY2__MODEL_ELEMENT2:
        return MODEL_ELEMENT2_EDEFAULT == null ? modelElement2 != null : !MODEL_ELEMENT2_EDEFAULT.equals(modelElement2);
      case TemporalLogicPackage.PROPERTY2__NEXT:
        return next != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (modelElement2: ");
    result.append(modelElement2);
    result.append(')');
    return result.toString();
  }

} //Property2Impl
