/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.uml.verification.tl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.uml.verification.tl.ui.internal.TlActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class TemporalLogicUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TlActivator.getInstance().getInjector("org.eclipse.uml.verification.tl.TemporalLogic");
	}

}
